# Default configuration for Financial QA System

processing:
  chunk_size: 1000
  chunk_overlap: 200

embedding:
  model_name: "sentence-transformers/all-MiniLM-L6-v2"
  device: "cpu"

retrieval:
  embedding_dimension: 384  # Depends on the embedding model
  index_type: "IndexFlatL2"
  top_k: 5

generation:
  model_name: "gpt-4"
  temperature: 0.0
  max_tokens: 1024
  max_context_length: 4000

hallucination:
  threshold: 70.0
  verification_rounds: 1
  weights:
    llm_confidence: 0.6
    retrieval_score: 0.2
    consistency_score: 0.2
